### ISSUE TITLE
Epic 1, User Story 1

### ISSUE THREAD

**Issue by Bendude5** [SchoolOfCode/bc17-w4d2-project-lbb7#2]
```[tasklist]
### Tasks
- [x] Amend readme with instructions
- [x] npm init to initialise
- [x] In json file, add type module line
- [x] Install Express
- [x] Create files
```
