### ISSUE TITLE
Epic 1, User Story 2

### ISSUE THREAD

**Issue by lanamauge** [SchoolOfCode/bc17-w4d2-project-lbb7#3]
```[tasklist]
### Tasks
- [x] Install helmet package - npm install helmet
- [x] Import helmet module to index.js
- [x] added app.use function to index.js
- [x] checked to see if the response header “X-Powered-By: Express” has been removed in postman
```
