### ISSUE TITLE
Epic 2 User Story 1

### ISSUE THREAD

**Issue by BenMaharjan** [SchoolOfCode/bc17-w4d2-project-lbb7#4]
```[tasklist]
### Tasks
- [x] Create an activities variable that will hold JSON data
- [x] Create a get function that will get data from the /activities directory
- [x] add a status (200) responce if the get function is succesful
```
