### ISSUE TITLE
Epic 2 User Story 2

### ISSUE THREAD

**Issue by BenMaharjan** [SchoolOfCode/bc17-w4d2-project-lbb7#5]
```[tasklist]
### Tasks
- [x] Create a post function that will allow a user to add data to the activities JSON object
- [x] Create a unique ID for each POST request
- [x] Create an error message if POST request has not been sent in the correct format
```
