### ISSUE TITLE
Epic 3, User Story 1

### ISSUE THREAD

**Issue by lanamauge** [SchoolOfCode/bc17-w4d2-project-lbb7#6]
```[tasklist]
### Tasks
- [ ] Create a put request which updates an activity
- [ ] Include status code - success or fail
- [ ] Add a key which includes 'data' and 'error'
- [ ] If it fails, respond with error message (response.error)
```
